// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen31HotelAPI.Models;

public partial class CarMaintenance
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime ActualStartTime { get; set; }

    public DateTime EndTime { get; set; }

    public DateTime ActualEndTime { get; set; }

    public string Action { get; set; }

    public decimal Expense { get; set; }

    public int EmpId { get; set; }
}