// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen31HotelAPI.Models;

public partial class CarOrder
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public DateTime BookingTime { get; set; }

    public decimal Total { get; set; }
}