// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen31HotelAPI.Models;

public partial class CarPrice
{
    public int Id { get; set; }

    public string LowDistance { get; set; }

    public string HighDistance { get; set; }

    public decimal Price { get; set; }
}