// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fuen31HotelAPI.Models;

public partial class CarResponsible
{
    public int Id { get; set; }

    public int CarId { get; set; }

    public int EmpId { get; set; }

    public virtual CarManagement Car { get; set; }
}